version: '3'
services:
  front_input:
    build: ./public
    image: front-input
    ports:
      - "3000:80"

  back:
    build:
      context: .
      dockerfile: Dockerfile.rpi
    image: back
    environment:
      - "PORT=8080"
    ports:
      - "8080:8080"
