version: '3'
services:
  front_input:
    build: ./public
    image: front-input
    ports:
      - "3000:80"

  back:
    build:
      context: .
      dockerfile: Dockerfile.rpi.debug
    image: back-debug
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - "PORT=8080"
    ports:
      - "8080:8080"
      - "40000:40000"
