version: '3'
services:
  front_input:
    build: ./public
    image: front-input
    ports:
      - "3000:80"

  back:
    build: .
    image: back
    environment:
      - "ENV=PROD"
      - "PORT=8080"
      - "LOG_LEVEL=TRACE"
    ports:
      - "8080:8080"
