version: 2
jobs:
  build:
    docker:
      - image: tmaier/docker-compose
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build, Test and Deploy
          command: |
            docker create --name ar_cicd \
                -e "SSH_USER=$SSH_USER" \
                -e "SSH_PASS=$SSH_PASS" \
                -e "SSH_SERVER=$SSH_SERVER" \
                -e "SSH_FOLDER=$SSH_FOLDER" \
                joaopio/animated-robot-cicd
            docker cp . ar_cicd:/go/src/animated-robot
            docker start -a ar_cicd
